general:
  domain: "example.com"
  appName: "revapp"
app:
  image: fooser/revapi:0.0.5
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  cpu: 60
ingress:
  host: "nginx"
config:
  TEST: "Development"
secrets:
  MONGO_URI: "mongo-uri"
