name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testing Bash env var
        run:  | 
          VERSION=$(head -n 1 ./VERSION)
          if [ -z $VERSION ]; then
            echo "Version in empty. Aborting."
            exit 1
          fi
          echo "version<<EOF" >> $GITHUB_ENV
          echo "$VERSION" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check variable
        run:  | 
          echo $VERSION

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/revapi:${{ env.VERSION }}
